### ISSUE TITLE
Should we remove links to workspaces that aren't publically available?

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BiocAnVIL#5]
On the [training](http://anvil.bioconductor.org/articles/training.html) page under Workspaces, I get a "Could not display workspace" for the AnVIL and Pan-cancer Transcriptome Surveys. Should we continue to list them if they aren't "publically" available?

**Comment by vjcitn** [comment]
good catch   i will ask for it to be made public    you could add (public release pending)
